### ISSUE TITLE
Application immediately crashes

### ISSUE THREAD

**Issue by LTrain** [Beta8397/virtual_robot#71]
The application immediately crashes after running it. 
This is a fresh install of java and intellij. Any thoughts on this error?

Exception in Application start method
Exception in Application stop method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:873)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javafx.fxml.LoadException: 
/C:/Users/leonp/Downloads/virtual_robot-master/virtual_robot-master/out/production/Controller/virtual_robot/controller/virtual_robot.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2571)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at virtual_robot.controller.VirtualRobotApplication.start(VirtualRobotApplication.java:22)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:187)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566)
	... 12 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
	at virtual_robot.controller.VirtualRobotController.setupCbxOpModes(VirtualRobotController.java:372)
	at virtual_robot.controller.VirtualRobotController.initialize(VirtualRobotController.java:135)
	... 22 more
Exception running application virtual_robot.controller.VirtualRobotApplication

Process finished with exit code 1

**Comment by LTrain** [comment]
Looks to be windows related - I was able to run it on a mac.

**Comment by jkenney2** [comment]
@LTrain 

By any chance are you using OpenJFX rather than the Java FX that is built in to JDK8 and Amazon Corretto? 

I did a fresh clone of virtual_robot, and it runs fine with Corretto. Then I switched to Java 11 and added a library for OpenJFX 11. That resulted in the same error you're seeing.

**Comment by LTrain** [comment]
Not sure I’ll check. I installed it to a cleaner machine and it worked fine. This is on a laptop I need to nuke and pave anyway. I’ll try that now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jkenney2** [comment]
If the issue on your laptop was related to using OpenJFX, what you'd probably need to do to fix it is to add "VM Options" in your Run Configuration, as is explained [here](https://openjfx.io/openjfx-docs/) in the "JavaFX and IntelliJ" tab. I'll close this issue; let me know if any more problems.

**Comment by LTrain** [comment]
That resolved the issue thanks for the fast support.

________________________________
